import net.dv8tion.jda.api.events.message.MessageReceivedEvent;
import net.dv8tion.jda.api.hooks.ListenerAdapter;
import org.jetbrains.annotations.NotNull;

import java.util.ArrayList;
import java.util.Random;

public class CommandSussy extends ListenerAdapter {

    private static final ArrayList<String> quotes = new ArrayList<>();
    Random rand = new Random();
    public CommandSussy() {
        quotes.add("Care to explain what you meant when you said it would be 'poggers' if you had a 'monster futa cock' to 'impregnate my boypussy' with, pyro-chan?");
        quotes.add("IM DELETING YOU, PYRO!:sob::wave::fire: ██]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]] 10% complete..... ████]]]]]]]]]]]]]]]]]]]]]]]]]]] 35% complete.... ███████]]]]]]]]]]]]]]]] 60% complete.... ███████████] 99% complete..... :no_entry_sign:ERROR!:no_entry_sign: :100:A True:100: Pyro :fire: is irreplaceable :sparkling_heart:I could never delete you Pyro!:sparkling_heart::fire: Send this to ten other :fire:Pyros:fire: who give you :sweat_drops:cummies:sweat_drops: Or never get called :cloud:retard:cloud: again:x::x::grimacing::grimacing::x::x: If you get 0 Back: no cummies for you :no_entry_sign::no_entry_sign::imp: 3 back: you're a retard :smiling_face_with_3_hearts::cloud::sweat_drops: 5 back: you're pyro's kitten:kissing_cat::angel::sweat_drops: 10+ back: Pyro :fire::stuck_out_tongue::stuck_out_tongue::two_hearts::two_hearts::sweat_drops::tongue::tongue:");
        quotes.add("as a person who has lots of sex all the time, i can say that this game is 100% accurate to having sex with sexy women. like i do. everyday. this game did not make me horny however. i am not gay. i just have too much sex with real women to spend more than 15 minutes in this game. on the other hand i would recommend this game to people who do not have sex (unlike me because i have lots of sex with women a lot) as there is a naked woman in it and she is naked. she kinda looks like one of my many girlfriends who i have sex with a lot. i have lots of sex. i also an very handsome and women ALWAYS want to have sex with me because i am very muscular and handsome and very good at video games. all my girlfriends say im very good at sex and playing video games and being handsome. one of my girlfriends asked me to have sex with her but i told her i was playing a sex game instead so she started crying and became a lesbian and killed herself because i did not have sex with her. i have sex with women. not men. i am not gay. i am very cool and handsome so girls always have sex with me because i am very cool and sexy. my penis is very big. all my girlfriends like my penis because it is very big and i am very good at sex with my women. every woman ive had sex with is very sexy and so am i. i have lots of sex. i am also very handsome and sexy and i have lots of sex.");
        quotes.add("Babe, I'm breaking up with you. It's not you, you were poggers. It's me, I'm omegalul. Im sorry if this is pepehands but it has to be done, I've just been feeling pepega and our relationship has been weirdchamp for months. It's time to end it, no kappa.");
        quotes.add("Rawr X3 nuzzles How are you? pounces on you you're so warm o3o notices you have a bulge someone's happy! nuzzles your necky wecky ~murr~ hehe ;) rubbies your bulgy wolgy you're so big! rubbies more on your bulgy wolgy it doesn't stop growing .///. kisses you and licks your neck daddy likes ;) nuzzle wuzzle I hope daddy likes wiggles butt and squirms I wanna see your big daddy meat! wiggles butt I have a little itch o3o wags tails can you please get my itch? put paws on your chest nyea~ it's a seven inch itch rubs your chest can you pwease? squirms pwetty pwease? :( I need to be punished runs paws down your chest and bites lip like, I need to be punished really good paws on your bulge as I lick my lips I'm getting thirsty. I could go for some milk unbuttons your pants as my eyes glow you smell so musky ;) licks shaft mmmmmmmmmmmmmmmmmmm so musky ;) drools all over your cawk your daddy meat. I like. Mister fuzzy balls. puts snout on balls and inhales deeply oh my gawd. I'm so hard rubbies your bulgy wolgy licks balls punish me daddy nyea~ squirms more and wiggles butt I9/11 lovewas an yourinside muskyjob goodness bites lip please punish me licks lips nyea~ suckles on your tip so good licks pre off your cock salty goodness~ eyes roll back and goes balls deep");
        quotes.add("WTF 状態 WYNNCRAFT IRL TRADE HACK??? 800 USD SALES STILL NOT BANNED? 注意中国 ー ー GETMADS IMMUNITY HACK - MODERATOR FAVOR SECRET?? 情報誌40000円 ANGRY ARAB MALDING METHOD - NO CREDIT CARD:::??::: 表示 PAYPAL DISPUTE INSTAWIN HACK - GUARANTEED QATAR OUTPLAY 400 USD TRICK @ UNDETECTED IN SAUDI ARABIA 興味深相手。今日 - MC-MARKET WYNNCRAFT INSTA RICH DARK TECHNOLOGY SCRIPT, NOT CAUGHT YET??????");
        quotes.add("Wynncraft Content Team are fantastic, they just need to work on coding, community outreach, bug fixing, economy management, game knowledge, quality assurance, hot fix speed, class balance, common sense, compensation rewards, content pacing, content creation, character progression, sense of humor, net coding, power creep, crates, transparency, server stability and customer support.");
        quotes.add("I stopped for awhile so im trying to get the gains back... I might not hit hard in Wynncraft but I hit hard IRL :rofl:");
        quotes.add("I really love Lari. Like, a lot. Like, a whole lot. You have no idea. I love her so much that it is inexplicable, and I'm ninety-nine percent sure that I have an unhealthy obsession. I will never get tired of doing the Realm of Light quests. It is my life goal to meet up with her in real life and just say hello to her. I fall asleep at night dreaming of her holding a personal light show for me, and then she would be so tired that she comes and cuddles up to me while we sleep together. If I could just hold her hand for a brief moment, I could die happy. If given the opportunity, I would lightly nibble on her ear just to hear what kind of sweet moans she would let out. Then, I would hug her while she clings to my body hoping that I would stop, but I only continue as she moans louder and louder. I would give up almost anything just for her to look in my general direction. No matter what I do, I am constantly thinking of her. When I wake up, she is the first thing on my mind. When I go to school, I can only focus on her. When I go come home, I go on the computer so that I can read her dialogue in the Realm of Light questline. When I go to sleep, I dream of her and I living a happy life together. She is my pride, passion, and joy. If she were to call me \"Onii-chan,\" I would probably get diabetes from her sweetness and die. I wish for nothing but her happiness. If it were for her, I would give my life without any second thoughts. Without her, my life would serve no purpose. I really love Lari.\n");
        quotes.add("I really love Mostima. Like, a lot. Like, a whole lot. You have no idea. I love her so much that it is inexplicable, and I'm ninety-nine percent sure that I have an unhealthy obsession. I will never get tired of listening that sweet, (fallen) angelic voice of hers. It is my life goal to meet up with her in real life and just say hello to her. I fall asleep at night dreaming of her holding my hand and take me around Terra, and then she would be sorry tired that she comes and cuddles up to me while we sleep together. If I could just hold her hand for a brief moment, I could die happy. I would give up almost anything just for her to look in my general direction. No matter what I do, I am constantly thinking of her. When I wake up, she is the first thing on my mind. When I go to work, I can only focus on her. When I come home, I get on Arknights instantly so that I can listen to her beautiful voice lines. When I go to sleep, I dream of her and I living a happy life together. She is my pride, passion, and joy. If she were to call me \"dokuta-kun,\" I would probably get diabetes from her sweetness and die. I wish for nothing but her happiness. If it were for her, I would give up my life and my 1000 hours Arknights account without any second thoughts. Without her, my life would serve no purpose. I really love Mostima.");
        quotes.add("I’m telling you, Xynode is as cracked as he is jacked. I saw him at a 7-11 the other day buying Coffee and adult diapers. I asked him what the diapers were for and he said ”they contain my full power so I don’t completely shit on these dragons“ then he rode a Sunspire Champion Senche-Lion out the door.");
        quotes.add("Hel am look veteran clear sunlightspire, am good play do 67k atronach dps tester (when not lag bit). am player good for warden stamina usage. I try clear for ice fire mount but guid have trouble for cat fighters on icing dragon. I view video of the 4 Days and no difernce make plays me and them, think am good for sunlightspire can do high dps atro for fas run mount get. I play stam warden aso play mana nitgeblade (teach by alcast), let know can play warden stam mana nigte let know not die red dodge all mech never die am good nitgeblade sunlight spire");
        quotes.add("As for sex with Weedy, I imagine it will go like this: You have sex with her like a normal girl but with her on top and you're holding hands, but in the height of arousal, she would insert her ovipositor into your urethra (It's a soft tentacle-like organ that extends from within her vagina). Ejaculation would ensue as you both orgasm simultaneously, and her ovipositor would meet your sperm halfway inside of your urethra, right on the prostate area (You'd feel a strong and deep sexual pressure), ensuring that your sperm would successfully fertilize her eggs with a 99% success rate (Excess fluids would be ejaculated past her ovipositor and into her vagina). This fertilizes the eggs, and these fertilized eggs, still inside you, would slowly travel backwards all throughout the vas deferens tubes, into the epididymis's and into your testicles, where they would attach themselves inside of them, safely rest, grow, and be nourished by the testicles. While they grow, they make your testicles work 10x their usual rate, and so you'd be much, much hornier than usual. This allows you to become very attached and intimate with Weedy during the period (This ensures a strong parental bond for the offspring). The eggs wouldn't grow very large at all. They are quite small, but there are up to 1500 of them, and they take from 9-45 days to finish growing. Once they're ready to hatch however, you have birthing sex with Weedy. It is very intimate and wild sex with her where at the peak of the act, you have an immensely powerful ejaculation and ejaculate the eggs into her vagina. They sit there briefly before she delivers them just like humans regularly would through labor. You pass out from the pleasure mid orgasm, and you awake to up to 1500 mini Weedy's and Weedy.");
        quotes.add("Xynode Gaming isn't so great? Are you kidding me? When was the last time you saw a player with such an ability and movement with Sorc? Xynode puts the game in another level, and we will be blessed if we ever see a player with his skill and passion for the game again. Kevduit breaks records. Alcast breaks records. Xynode breaks the rules. You can keep your statistics. I prefer the magic.");
        quotes.add("put on the fucking femboy outfit pyro");
    }

    @Override
    public void onMessageReceived(@NotNull MessageReceivedEvent event) {
        String msg = event.getMessage().getContentRaw();
        if (msg.startsWith(Main.bot.settings.getPrefix(event.getGuild().toString())) && msg.indexOf("sussy") == Main.bot.settings.getPrefix(event.getGuild().toString()).length() && msg.length() == Main.bot.settings.getPrefix(event.getGuild().toString()).length() + "sussy".length()) {
            int i = rand.nextInt(quotes.size());
            String message = quotes.get(i);

            Bot.sendMessage(event.getChannel(), message, false);
        }
    }
}
